# Generated by Django 4.0.4 on 2022-08-06 22:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_alter_project_contact'),
        ('contact', '0002_remove_company_phone_company_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=8, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('prevailing_rate', models.BooleanField(default=False)),
                ('travel_job', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contact.address')),
                ('contacts', models.ManyToManyField(blank=True, to='contact.contact')),
                ('customers', models.ManyToManyField(blank=True, null=True, to='contact.company')),
                ('project_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectcategory')),
                ('project_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttype')),
            ],
        ),
    ]
