# Generated by Django 4.0.4 on 2022-11-09 22:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=8, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('due', models.DateField()),
                ('prevailing_rate', models.BooleanField(default=False)),
                ('travel_job', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('revision', models.IntegerField(default=0, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contact.address')),
                ('customers', models.ManyToManyField(blank=True, to='contact.company')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectcategory')),
                ('project_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttype')),
            ],
        ),
    ]
