# Generated by Django 4.0.4 on 2022-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_company_phone_company_phone'),
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='customers',
            field=models.ManyToManyField(blank=True, to='contact.company'),
        ),
    ]
