# Generated by Django 4.0.4 on 2022-09-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_quote_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='due',
            field=models.DateField(null=True),
        ),
    ]
