# Generated by Django 4.0.4 on 2022-09-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_quote_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='due',
            field=models.DateField(),
        ),
    ]
