# Generated by Django 4.0.4 on 2022-12-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_alter_quote_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='year',
        ),
    ]
