# Generated by Django 4.0.4 on 2022-12-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_remove_quote_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
