# Generated by Django 4.0.4 on 2022-09-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_quote_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
