# Generated by Django 4.0.4 on 2022-09-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_quote_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='revision',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
