# Generated by Django 4.0.4 on 2022-10-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_quote_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
