# Generated by Django 4.0.4 on 2022-10-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_alter_quote_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='contacts',
        ),
    ]
