# Generated by Django 4.0.4 on 2022-05-11 22:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import worksegment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('date', models.DateField(null=True, validators=[worksegment.models.no_future])),
                ('isoweek', models.CharField(blank=True, editable=False, max_length=8)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('lunch', models.BooleanField(default=True)),
                ('travel_duration', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('duration', models.DurationField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='worksegment',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lte', django.db.models.expressions.F('end_time'))), name='start_before_end'),
        ),
    ]
