# Generated by Django 4.0.4 on 2022-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksegment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksegment',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=5, null=True),
        ),
    ]
