# Generated by Django 4.0.4 on 2022-08-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksegment', '0003_alter_worksegment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksegment',
            name='segment_type',
            field=models.CharField(default='field', max_length=100),
            preserve_default=False,
        ),
    ]
