# Generated by Django 4.0.4 on 2022-12-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksegment', '0003_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksegment',
            name='segment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksegment.worktype'),
        ),
    ]
