# Generated by Django 4.0.4 on 2022-05-25 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='memo',
            field=models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
