# Generated by Django 4.0.4 on 2022-05-25 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='memo',
            field=models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
