# Generated by Django 4.0.4 on 2022-11-09 22:49

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.us.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=1024, verbose_name='Place ID')),
                ('address', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('state', models.CharField(max_length=200, null=True)),
                ('postal_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('phone_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Main', 'Main'), ('Work', 'Work'), ('Home', 'Home'), ('Direct', 'Direct'), ('Fax', 'Fax')], default='Mobile', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contact.company')),
                ('fax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contact.phone')),
                ('phone', models.ManyToManyField(blank=True, to='contact.phone')),
            ],
        ),
    ]
