# Generated by Django 4.0.4 on 2022-11-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('contact', '0001_initial'),
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='projects',
            field=models.ManyToManyField(blank=True, to='project.project'),
        ),
        migrations.AddField(
            model_name='contact',
            name='quotes',
            field=models.ManyToManyField(blank=True, to='quote.quote'),
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contact.phone'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.ManyToManyField(blank=True, to='contact.phone'),
        ),
    ]
