# Generated by Django 4.0.4 on 2022-05-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.ManyToManyField(blank=True, to='contact.phone'),
        ),
    ]
