# Generated by Django 4.0.4 on 2022-12-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_hse_created_alter_project_created_and_more'),
        ('contact', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='hses',
            field=models.ManyToManyField(blank=True, to='project.hse'),
        ),
        migrations.AddField(
            model_name='contact',
            name='services',
            field=models.ManyToManyField(blank=True, to='project.service'),
        ),
    ]
