# Generated by Django 4.0.4 on 2022-08-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_company_phone_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='place_id',
            field=models.CharField(default=1, max_length=1024, verbose_name='Place ID'),
            preserve_default=False,
        ),
    ]
