# Generated by Django 4.0.4 on 2022-09-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_zip_code_address_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address2',
        ),
    ]
