# Generated by Django 4.0.4 on 2022-10-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_remove_quote_contacts'),
        ('contact', '0006_alter_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='quotes',
            field=models.ManyToManyField(blank=True, to='quote.quote'),
        ),
    ]
