# Generated by Django 4.0.4 on 2022-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_contact_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
