# Generated by Django 4.0.4 on 2022-10-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contact_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home'), ('Direct', 'Direct')], default='Mobile', max_length=200, null=True),
        ),
    ]
