# Generated by Django 4.0.4 on 2022-10-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_phone_phone_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='fax',
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home'), ('Direct', 'Direct'), ('Fax', 'Fax')], default='Mobile', max_length=200, null=True),
        ),
    ]
