# Generated by Django 4.0.4 on 2022-10-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_remove_contact_fax_alter_phone_phone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contact.phone'),
        ),
    ]
