# Generated by Django 4.0.4 on 2022-11-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_alter_contact_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Main', 'Main'), ('Work', 'Work'), ('Home', 'Home'), ('Direct', 'Direct'), ('Fax', 'Fax')], default='Mobile', max_length=200, null=True),
        ),
    ]
