# Generated by Django 4.0.4 on 2022-11-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_alter_phone_phone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contact.phone'),
        ),
    ]
