# Generated by Django 4.0.4 on 2022-06-17 08:56

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_pic',
            field=imagekit.models.fields.ProcessedImageField(default='None', upload_to='receipt_pic'),
        ),
    ]
