# Generated by Django 4.0.4 on 2022-06-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt_pic',
        ),
    ]
