# Generated by Django 4.0.4 on 2022-06-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_receipt_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
