# Generated by Django 4.0.4 on 2022-06-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expense_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month',
        ),
    ]
