# Generated by Django 4.0.4 on 2022-06-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_alter_expense_receipt_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mile',
            old_name='date',
            new_name='date_purchased',
        ),
    ]
