# Generated by Django 4.0.4 on 2022-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_rename_date_mile_date_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='milerate',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
