# Generated by Django 4.0.4 on 2022-06-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
