# Generated by Django 4.0.4 on 2022-06-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
