# Generated by Django 4.0.4 on 2022-07-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='due',
        ),
    ]
