# Generated by Django 4.0.4 on 2022-07-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_remove_subtask_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='is_deleted',
        ),
    ]
