# Generated by Django 4.0.4 on 2022-08-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_alter_quote_customers'),
        ('task', '0012_remove_subtask_created_remove_subtask_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quote.quote'),
        ),
    ]
