# Generated by Django 4.0.4 on 2022-09-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_quote_due'),
        ('task', '0013_task_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.quote'),
        ),
    ]
