# Generated by Django 4.0.4 on 2022-11-14 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=8, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('terms', models.CharField(max_length=200, null=True)),
                ('prevailing_rate', models.BooleanField(default=False)),
                ('union', models.BooleanField(default=False)),
                ('certified_payroll', models.BooleanField(default=False)),
                ('material_only', models.BooleanField(default=False)),
                ('travel_job', models.BooleanField(default=False)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contact.address')),
                ('billing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.billingtype')),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.ordertype')),
                ('project_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectcategory')),
                ('project_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttype')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=8, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('terms', models.CharField(max_length=200, null=True)),
                ('prevailing_rate', models.BooleanField(default=False)),
                ('union', models.BooleanField(default=False)),
                ('certified_payroll', models.BooleanField(default=False)),
                ('material_only', models.BooleanField(default=False)),
                ('travel_job', models.BooleanField(default=False)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contact.address')),
                ('billing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.billingtype')),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.ordertype')),
                ('project_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectcategory')),
                ('project_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttype')),
            ],
        ),
        migrations.CreateModel(
            name='HSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=8, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('terms', models.CharField(max_length=200, null=True)),
                ('prevailing_rate', models.BooleanField(default=False)),
                ('union', models.BooleanField(default=False)),
                ('certified_payroll', models.BooleanField(default=False)),
                ('material_only', models.BooleanField(default=False)),
                ('travel_job', models.BooleanField(default=False)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contact.address')),
                ('billing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.billingtype')),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.ordertype')),
                ('project_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectcategory')),
                ('project_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttype')),
            ],
        ),
    ]
