# Generated by Django 4.0.4 on 2022-08-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_company_phone_company_phone'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.ManyToManyField(blank=True, to='contact.contact'),
        ),
    ]
