# Generated by Django 4.0.4 on 2022-11-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_initial'),
        ('project', '0002_hse_po_number_project_po_number_service_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contact.company'),
            preserve_default=False,
        ),
    ]
