# Generated by Django 4.0.4 on 2022-11-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_billingtype_ordertype_project_certified_payroll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertype',
            name='code',
        ),
    ]
