# Generated by Django 4.0.4 on 2022-09-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='code',
            field=models.CharField(default='ccc', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
