# Generated by Django 4.0.4 on 2022-10-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectcategory_code_alter_projecttype_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contact',
        ),
    ]
