# Generated by Django 4.0.4 on 2022-11-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_hse_customer_service_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hse',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
