# Generated by Django 4.0.4 on 2022-11-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSE',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.project')),
            ],
            bases=('project.project',),
        ),
    ]
