# Generated by Django 4.0.4 on 2022-10-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='customer_company',
        ),
    ]
