# Generated by Django 4.0.4 on 2022-12-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_hse_created_project_created_service_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hse',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
