# Generated by Django 4.0.4 on 2022-12-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_hse_created_alter_project_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttype',
            name='project_category',
        ),
        migrations.AddField(
            model_name='projecttype',
            name='project_category',
            field=models.ManyToManyField(blank=True, to='project.projectcategory'),
        ),
    ]
